# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run API test and publish report

on:
  push:
    branches: [ main ]

jobs:
  APIAutomationBuild:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/setup-node@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3.2.0

    - name: Build Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        load: true
        tags: api-node-image:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
    
    - name: Run api test in docker
      run: docker run --volume "${pwd}"/report:/app/report/ api-node-image:latest

    - name: Upload report artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: MochawesomeReport
        path: /report

    # - name: Deploy report to GitHub Page
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       PUBLISH_BRANCH: gh-pages
    #       PUBLISH_DIR: ./report